server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

  spring:
    datasource:
      username: root
      password: password
      url: jdbc:mysql://34.68.28.152/project1
#      driver-class-name:
    jpa:
      hibernate:
        ddl-auto:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true

